### ISSUE TITLE
Complete the current user support within Firebase

### ISSUE THREAD

**Issue by Jharaxus** [polypoly-team/android-app#32]
- [x] Fix support of a list of existing user in Firebase (missing in [#21](https://github.com/polypoly-team/android-app/pull/21))
- [x] Add tests for PR [#21](https://github.com/polypoly-team/android-app/pull/21)

**Comment by Jharaxus** [comment]
- [ ] Fix list of existing user support in Firebase
- [ ] Add tests for PR [#21](https://github.com/polypoly-team/android-app/pull/21)
